#!/bin/sh
set -e

AUTH_MATCH='.+\s.+'
BASIC_DEFAULT_USER=admin
BASIC_DEFAULT_PASS=admin

if [ "$OVERRIDE_CERT" == "" ]; then
    # Generate OpenSSL private key
    openssl genrsa -out /etc/ssl/private/apache-selfsigned-key.default 2048

    # Generate OpenSSL certificate
    openssl req -x509 -newkey rsa:4096 \
    -key /etc/ssl/private/apache-selfsigned-key.default \
    -out /etc/ssl/certs/apache-selfsigned.crt \
    -subj "/C=US/ST=WA/L=Seattle/O=F5 Networks/OU=PD/CN=localhost/emailAddress=support@f5.com"
else
    echo "WARNING: Default SSL cert generation overriden"
fi

# Apache gets grumpy about PID files pre-existing
rm -f /usr/local/apache2/logs/httpd.pid

if [ -z "$AUTH" ];
    then
        echo "WARNING: username and password is currently set to default values"
        htpasswd -b -c /etc/www/pass/htpasswd.user "$BASIC_DEFAULT_USER" "$BASIC_DEFAULT_PASS"
elif echo "$AUTH" | grep -Eq "$AUTH_MATCH";
    then
        ENV_USER=$(echo $AUTH | cut -d ' ' -f 1)
        ENV_PASS=$(echo $AUTH | cut -d ' ' -f 2)
        htpasswd -b -c /etc/www/pass/htpasswd.user $ENV_USER $ENV_PASS
elif [ "$AUTH" = "DISABLE" ];
    then
    > /etc/www/pass/htpasswd.user
    > /usr/local/apache2/conf/auth/basic.conf
    echo "WARNING: Basic Auth has been disabled"
elif [ "$AUTH" = "CUSTOM" ];
    then
	echo "WARNING: Running CUSTOM mode, assumes correct files have been mounted"
else
	echo "ERROR: Incorrect AUTH parameter specified"
fi

exec httpd -DFOREGROUND
