#!/bin/sh

export NODE_PATH='/usr/lib/node_modules:/usr/share/rest/node/node_modules'
run_in_debug=""
if [ $DEBUG ]; then
    run_in_debug=" --inspect=0.0.0.0:9229 "
fi

Options=""
if [ $BE_DB_TYPE ]; then
    Options=" --dbType=${BE_DB_TYPE}"
fi

if [ $BE_DB_CONN_STR ]; then
    Options="${Options} --connectionString ${BE_DB_CONN_STR}"
fi

if [ $NODE_COLLECTIONS ]; then
    Options="${Options} --enableCollectionWorkerFeature"
fi

if [ $NODE_LOGLEVEL ]; then
    Options="${Options} --logLevel=${NODE_LOGLEVEL}"
fi

if [ $NODE_LOGLEVEL_CONSOLE ]; then
    Options="${Options} --logLevelConsole=${NODE_LOGLEVEL_CONSOLE}"
fi

if [ $NODE_PORT ]; then
    Options="${Options} -p ${NODE_PORT}"
else
    Options="${Options} -p 8105"
fi



exec node ${run_in_debug} /usr/share/rest/node/src/restnode.js ${Options} -c true -i /var/log/restnoded/restnoded.log -s none -u '' -g '' > /var/log/restnoded.out 2>&1
