# multi-stage build
FROM alpine:3.14 AS f5-icontrol-gateway

# Add VERSION file
COPY VERSION /

# Install infrastructure - nginx, hpasswd tools from apache2-utils, 
# runit, curl to download f5 packages from artifactory, openssl to create certs  
RUN apk --update add openjdk7-jre-base nodejs npm nodejs-dev bash runit git

# Hack fix to openjdk7-jre-base where this file was left out to support SSL TLS
COPY src/sunec.jar /usr/lib/jvm/java-1.7-openjdk/jre/lib/ext/
# Remove crypto algorithum which fail older jar test
RUN sed -i 's/X9.62 c2tnb191v1,//g' /usr/lib/jvm/java-1.7-openjdk/jre/lib/security/java.security && \
    sed -i 's/X9.62 c2tnb191v2,//g' /usr/lib/jvm/java-1.7-openjdk/jre/lib/security/java.security && \
    sed -i 's/X9.62 c2tnb191v3,//g' /usr/lib/jvm/java-1.7-openjdk/jre/lib/security/java.security && \
    sed -i 's/X9.62 c2tnb239v1,//g' /usr/lib/jvm/java-1.7-openjdk/jre/lib/security/java.security && \
    sed -i 's/X9.62 c2tnb239v2,//g' /usr/lib/jvm/java-1.7-openjdk/jre/lib/security/java.security && \
    sed -i 's/X9.62 c2tnb239v3,//g' /usr/lib/jvm/java-1.7-openjdk/jre/lib/security/java.security && \
    sed -i 's/X9.62 c2tnb359v1,//g' /usr/lib/jvm/java-1.7-openjdk/jre/lib/security/java.security && \
    sed -i 's/X9.62 c2tnb431r1,//g' /usr/lib/jvm/java-1.7-openjdk/jre/lib/security/java.security && \
    sed -i 's/X9.62 prime192v2,//g' /usr/lib/jvm/java-1.7-openjdk/jre/lib/security/java.security && \
    sed -i 's/X9.62 prime192v3,//g' /usr/lib/jvm/java-1.7-openjdk/jre/lib/security/java.security && \
    sed -i 's/X9.62 prime239v1,//g' /usr/lib/jvm/java-1.7-openjdk/jre/lib/security/java.security && \
    sed -i 's/X9.62 prime239v2,//g' /usr/lib/jvm/java-1.7-openjdk/jre/lib/security/java.security && \
    sed -i 's/X9.62 prime239v3,//g' /usr/lib/jvm/java-1.7-openjdk/jre/lib/security/java.security

# Add ln to specific Java7 required by F5 restjavad
RUN ln -s /usr/lib/jvm/java-1.7-openjdk/jre/bin/java /usr/bin/java7

# Install F5 restjavad packages
COPY restjavad/restjavad.tar.gz /
RUN cd / && \
    tar -xzf restjavad.tar.gz

# restjavad files
COPY config/etc/keystore.jks  /etc/keystore.jks
COPY config/etc/keystore.pwd  /etc/keystore.pwd
COPY config/etc/quartz.properties  /etc/quartz.properties
COPY config/etc/restjavad.log.conf /etc/restjavad.log.conf
COPY config/etc/rest.container.properties /etc/rest.container.properties
RUN mkdir -p /etc/service/restjavad/
COPY config/etc/service/restjavad/ /etc/service/restjavad/

# Install TrustDevice/TrustedProxy unit application
RUN mkdir -p /var/lib/f5-icontrol-trusted-devices && \
cd /var/lib && \
git clone https://github.com/f5devcentral/f5-icontrol-trusted-devices.git && \
cd f5-icontrol-trusted-devices && \
npm install
COPY config/etc/service/f5-icontrol-trusted-devices-express/ /etc/service/f5-icontrol-trusted-devices-express/

# Configure runit process manager
RUN mkdir -p /etc/runit/
COPY runit/ /etc/runit/
RUN chmod +x /etc/runit/1 /etc/runit/2 /etc/runit/3 /etc/runit/boot

EXPOSE 8105

ENTRYPOINT ["/etc/runit/boot"]
