#!/bin/sh
set -e

AUTH_MATCH='.+\s.+'
BASIC_DEFAULT_USER=admin
BASIC_DEFAULT_PASS=admin

if [ "$OVERRIDE_CERT" == "" ]; then
    # Generate OpenSSL private key
    openssl genrsa -out /etc/ssl/private/nginx-selfsigned-key.default 2048

    # Generate OpenSSL certificate
    openssl req -x509 -newkey rsa:4096 \
    -key /etc/ssl/private/nginx-selfsigned-key.default \
    -out /etc/ssl/certs/nginx-selfsigned.crt \
    -subj "/C=US/ST=WA/L=Seattle/O=F5 Networks/OU=PD/CN=localhost/emailAddress=support@f5.com"
else
    echo "WARNING: Default SSL cert generation overriden"
fi

# Apache gets grumpy about PID files pre-existing
rm -f /var/run/nginx.pid

if [ -z "$AUTH" ];
    then
        echo "WARNING: username and password is currently set to default values"
        htpasswd -b -c /etc/www/pass/htpasswd.user "$BASIC_DEFAULT_USER" "$BASIC_DEFAULT_PASS"
elif echo "$AUTH" | grep -Eq "$AUTH_MATCH";
    then
        ENV_USER=$(echo $AUTH | cut -d ' ' -f 1)
        ENV_PASS=$(echo $AUTH | cut -d ' ' -f 2)
        htpasswd -b -c /etc/www/pass/htpasswd.user $ENV_USER $ENV_PASS
elif [ "$AUTH" = "DISABLE" ];
    then
    > /etc/www/pass/htpasswd.user
    /bin/sed -i '/#__START_AUTH_SETTINGS__#/,/#__STOP_AUTH_SETTINGS__#/d' /etc/nginx/auth.conf
    echo "WARNING: Basic Auth has been disabled"
elif [ "$AUTH" = "CUSTOM" ];
    then
	echo "WARNING: Running CUSTOM mode, assumes correct files have been mounted"
else
	echo "ERROR: Incorrect AUTH parameter specified"
fi

has_api_key=$(grep 'set \$api_key' /etc/nginx/apigateway.conf | wc -l)
if [ "$has_api_key" == "1" ]
then 
    envsubst '${X_API_KEY}' < /etc/nginx/apigateway.conf 
fi

exec /usr/sbin/nginx -g "daemon off;";

